name: auto_animated_list
description: A Flutter ListView that implicitly animates between the changes of
  two lists with the support to reorder its items.
version: 0.5.2
homepage: https://github.com/wwwdata/implicitly_animated_reorderable_list

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  async: ">=2.8.1 <3.0.0"
  flutter:
    sdk: flutter
  meta: ">=1.7.0 <2.0.0"
  super_sliver_list: ">=0.4.1 <0.5.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
